services:
  santa_labyrinth_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    env_file:
      - .backend-env-file.env
    volumes:
      - ./api:/app
  
  santa_labyrinth_front:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: frontzin_torado
    ports:
      - 3000:3000
    volumes:
      - ../front/src:/front/src
      - ../front/public:/front/public